### ISSUE TITLE
Sekiro not being recognized

### ISSUE THREAD

**Issue by amferreiro** [leaty/tuxtrain#8]
Hello, dont know if im doing something wrong but sekiro is not being recognized by tuxtrained

Steps:
1. Downloaded from the ARU
2. Copied sekiro.toml from the repo into /etc/tuxtrain
3. Execute sudo tuxtrained
4. Launch sekiro in Steam

**Comment by leaty** [comment]
Sorry, I haven't had time to work on this for a while, but the current release 0.0.4 has a bug affecting sekiro (it has been fixed in master though). But I just released a [tuxtrain-git](https://aur.archlinux.org/packages/tuxtrain-git) AUR package you can use instead before the next release.

With this package all the trainers are installed into the `/usr/share/tuxtrain/` directory, of which you can copy the ones you want into the `/etc/tuxtrain/` directory.

Make sure to also edit the sekiro trainer to enable it `enable = true` as well as enabling the features you want. Note that the "Fix game speed for framelock" feature does not work for me.

To then run tuxtrain you have either of these options:
```bash
# Starts the daemon as a service, and on startup
sudo systemctl enable --now tuxtraind

# Starts the daemon in terminal
sudo tuxtraind

# Runs tuxtrain trainers one time only
# (i.e. you should only run this once after starting the game)
sudo tuxtrain
```

Hope that helps!

**Comment by amferreiro** [comment]
Problem fixed, thanks!
